-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS menu_contents
(
    id INT GENERATED BY DEFAULT AS IDENTITY,
    client_id INT NOT NULL REFERENCES clients(id),
    file_name VARCHAR NOT NULL,
    product_name VARCHAR NOT NULL,
    product_id VARCHAR NOT NULL,
    product_category VARCHAR NOT NULL,
    content VARCHAR NOT NULL,
    --896 for qwen2.5:0.5b; 2560 for qwen3:4b, 768 for embeddinggemma & nomic-embed-text & snowflake-arctic-embed:137m;
    --384 for snowflake-arctic-embed:33m; 1024 for snowflake-arctic-embed:335m
    content_vector VECTOR(768) NULL, 
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP DEFAULT NULL,
    PRIMARY KEY (id, client_id),
    UNIQUE(client_id, product_id)
);

CREATE INDEX IF NOT EXISTS idx_content_menu_client_id_deleted_at ON menu_contents(client_id) WHERE deleted_at IS NULL;

-- CREATE INDEX IF NOT EXISTS menu_contents_content_vector ON menu_contents USING HNSW (content_vector vector_cosine_ops);


CREATE INDEX IF NOT EXISTS idx_menu_contents_product_name_bm25 ON menu_contents USING bm25(product_name) WITH (text_config='german');
CREATE INDEX IF NOT EXISTS idx_menu_contents_product_id_bm25 ON menu_contents USING bm25(product_id) WITH (text_config='german');
CREATE INDEX IF NOT EXISTS idx_menu_contents_product_category_bm25 ON menu_contents USING bm25(product_category) WITH (text_config='german');

-- +goose StatementEnd

-- +goose Down
DROP TABLE IF EXISTS menu_contents;